serverID: 'none' #Your server ID will generate here
kicks:
  message: "&cProxies/VPNs are not allowed on this server!"
  enabled: true
  op-bypass: true
alerts:
  enabled: true
  message: '&7[&eOtter&7] &f%player% &7has joined on a VPN/proxy!'

ipLimiter:
  enabled: true
  limit: 3

