#If you do not have a license, we'll generate one for you
license: 'none'

# Blocks VPNs/Proxies from joining your server
antiVPN:
  enabled: true # enable or disable this feature
  alerts:
    enabled: true # should players receive alerts
    console: true # Should alerts send to console
    # The alert message staff will receive if someone joins on a VPN/Proxy
    message: '&7[&3Owl&7] &f%player% &7has joint on a &fVPN/proxy'
  punishment:
    enabled: true # enable or disable punishments for this feature
    opBypass: true # Should OPs bypass punishments
    message: '&cVPNs/Proxies are not enabled on this server!'

# Limits the amount of connections on one single IP address.
ipLimiter:
  enabled: true # enable or disable this feature
  limit: 2 # how many players can join on the same IP
  message: '&cYou have reached your IP connection limit!'
